name: Trigger Jenkins Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    types: [closed]
    branches: [ master ]

jobs:
  trigger-jenkins:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Trigger Jenkins Job
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.JENKINS_WEBHOOK_URL }}
        headers: '{"Jenkins-Crumb": "${{ secrets.JENKINS_CRUMB }}"}'
        body: '{"parameter": [{"name": "GIT_BRANCH", "value": "master"}, {"name": "GIT_COMMIT", "value": "${{ github.sha }}"}]}'
        
    - name: Notify team on Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author
        custom_payload: |
          {
            "attachments": [
              {
                "color": "good",
                "title": "Deployment triggered for ${{ github.repository }}",
                "text": "Jenkins pipeline has been triggered for deployment of the latest master branch code.\nCommit: ${{ github.sha }}\nAuthor: ${{ github.actor }}",
                "footer": "GitHub Actions",
                "footer_icon": "https://github.githubassets.com/favicon.ico"
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 